# Generated by Django 4.0.5 on 2022-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureVesselStressApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('IN', 'Inner'), ('OUT', 'Outer')], max_length=100)),
                ('capped', models.CharField(choices=[('C', 'Capped'), ('U', 'Uncapped')], max_length=100)),
                ('pouter', models.FloatField(max_length=100)),
                ('pinner', models.FloatField(max_length=100)),
                ('douter', models.FloatField(max_length=100)),
                ('dinner', models.FloatField(max_length=100)),
            ],
        ),
    ]
