# Generated by Django 4.0.5 on 2022-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVSmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surface', models.CharField(choices=[('IN', 'Inner Surface'), ('OUT', 'Outer Surface')], default='Inner Surface', max_length=5)),
                ('Capped?', models.CharField(choices=[('C', 'Capped'), ('U', 'Uncapped')], default='Capped', max_length=8)),
                ('Inner Pressure', models.FloatField()),
                ('Outer Pressure', models.FloatField()),
                ('Inner Diameter', models.FloatField()),
                ('Outer Diameter', models.FloatField()),
            ],
        ),
    ]
